### ISSUE TITLE
Updates in InMem execution don't create records

### ISSUE THREAD

**Issue by 2sComplement** [et1975/FsCassy#2]
In Cassandra, a partial update will create a row if it doesn't already exist. This is not the case with InMem interpreters which have no effect in the same circumstance. After debugging the `execute` function of the InMem interpreter it seems that non-trivial changes are required to the InMem pipeline to handle this case.

One workaround is to "seed" the array with values so they can be updated.

What are your thoughts on how to fix this?

**Comment by et1975** [comment]
Hmm, I see...
I'd transform the `where` expression into record construction. Maybe through `FSharp.Reflection`, which has a way to constructor a record from `obj []` of field values; from the `where` expression we can extract the desired field values, the rest can be `default`. A minor complication would be mapping field values to the position in the constructor `obj []` , but examining the record type should return them in the same order as the record constructor takes, so it's doable.

**Comment by 2sComplement** [comment]
Thanks, I'll look into doing it that way.
